name: Flask CI/CD Workflow

on:
  push:
    branches: [ main ]
jobs:
  build:
    name: Build Docker Image
    runs-on: ubuntu-latest
    outputs:
      image-tags: ${{ steps.meta.outputs.tags }}
    steps:
     - name: Checkout Code
       uses: actions/checkout@v4
     - name: Set up Docker Buildx
       uses: docker/setup-buildx-action@v3
     - name: Login to DockerHub
       uses: docker/login-action@v3
       with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

     - name: Build & Cache Docker Image (Multi-Platform)
       uses: docker/build-push-action@v5
       with:
        context: .
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        platforms: linux/amd64
        cache-from: type=gha
        cache-to: type=gha,mode=max
